#! /bin/sh

source "$HOME/.themerc"

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         10
bspc config focused_border_color $COLOR3
bspc config normal_border_color $COLOR4
bspc config window_gap          20

bspc config top_padding 35
bspc config right_padding 190
bspc config bottom_padding 50
bspc config left_padding 35

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ $LIGHTWEIGHT -neq 1 ]
then
    picom &
fi

feh --bg-fill "$HOME/Pictures/Backgrounds/bg0.png"

bash "$HOME/ui/bottombar.sh" &

bash "$HOME/ui/sidebar.sh" &
