[general]
live_config_reload = true

import = [
    "~/.config/alacritty/hardhacker.toml"
]

[window]
  opacity = 0.97
  dynamic_padding = true

[font]
  normal = { family = "DepartureMono Nerd Font", style = "Regular" }
  size = 16.5

[colors]
  cursor = { text = "#121212", cursor = "#f00fa0" }
  vi_mode_cursor = { text = "#121212", cursor = "#b00fc0" }
  transparent_background_colors = true

[cursor]
  style = { shape = "Block", blinking = "Off" }
  vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
  hide_when_typing = false
