[general]
live_config_reload = true

import = [
    "~/.config/alacritty/themes/ayu_dark.toml"
]

[window]
  opacity = 0.85
  dynamic_padding = true

[font]
  normal = { family = "Lilex Nerd Font", style = "Regular" }
  size = 11

[colors]
  cursor = { text = "#121212", cursor = "#30ff30" }
  vi_mode_cursor = { text = "#121212", cursor = "#00cf00" }
  transparent_background_colors = true

[cursor]
  style = { shape = "Block", blinking = "Off" }
  vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
  hide_when_typing = false
