live_config_reload = true

[window]
  decorations = "None"
  opacity = 0.92
  blur = true
  dynamic_padding = true

[font]
  normal = { family = "Hack Nerd Font Mono", style = "Regular" }
  size = 11.2

[colors]
  cursor = { text = "#121212", cursor = "#cf40ff" }
  vi_mode_cursor = { text = "#121212", cursor = "#af30ff" }
  transparent_background_colors = true

[cursor]
  style = { shape = "Block", blinking = "Off" }
  vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
  hide_when_typing = true
